### PR TITLE
layer.conf: Add warrior to compatible release series

### PR DESCRIPTION
**Pull request by pattivacek**

### CODE REVIEW

**Comment by pattivacek** [comment]
FYI @mike-sul.

**Review by mike-sul — COMMENTED** [review]
I had to add 'warrior' to a few other places in order to be able to bitbake an image, specifically ./meta-openembedded/meta-filesystems/conf/layer.conf:18:LAYERSERIES_COMPAT_filesystems-layer = "thud warrior"

**Comment by pattivacek** [comment]
@mike-sul `meta-openembedded` is a separate repository outside of our control, sounds like you just need to `repo sync` to get the latest version... unless they really really haven't bumped it yet. You can also submit a patch to them if you'd like.

**Comment by mike-sul** [comment]
> @mike-sul `meta-openembedded` is a separate repository outside of our control, sounds like you just need to `repo sync` to get the latest version... unless they really really haven't bumped it yet. You can also submit a patch to them if you'd like.

Yes, your're right, it's working now (https://github.com/openembedded/meta-openembedded/commit/0435c9e193f53193a8f0043ddc287d061f72f250)

**Review by lbonn — APPROVED** [review]

**Pull request merged**
