### PR TITLE
Ci/ota 3734/gitlab ci job

### PR DESCRIPTION
**Pull request by mike-sul**

### CODE REVIEW

**Comment by mike-sul** [comment]
@lbonn The meta-updater-raspberry might need a fix similar to the one in this PR,
see https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater-raspberrypi/-/jobs/674819
it uses `TEST_MACHINE=qemux86-64` by default.

**Comment by pattivacek** [comment]
Interesting, not sure why the `TEST_MACHINE` thing would behave differently.

What is the merge commit for? Seems like you can safely drop that.

**Comment by mike-sul** [comment]
> Interesting, not sure why the `TEST_MACHINE` thing would behave differently.
> 
> What is the merge commit for? Seems like you can safely drop that.

 `TEST_MACHINE` defines the param for meta-updater/scripts/envsetup.sh. and it behaves consistently. The raspberrypi CI job is not defined quite correct, it should include `TEST_MACHINE=raspberrypi3` here https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/master/.gitlab-ci.yml#L56.


The merge commit has been dropped.

**Comment by pattivacek** [comment]
> The raspberrypi CI job is not defined quite correct, it should include `TEST_MACHINE=raspberrypi3` here https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/master/.gitlab-ci.yml#L56.

It looks like it is set in the build step (https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/master/.gitlab-ci.yml#L46); does it really matter for the selftest step as well? It makes sense to set it, but I'm curious how it's working for RPi now then.

> The merge commit has been dropped.

Thanks!

**Comment by mike-sul** [comment]
> t looks like it is set in the build step (https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/master/.gitlab-ci.yml#L46); does it really matter for the selftest step as well? It makes sense to set it, but I'm curious how it's working for RPi now then.

That's another job executed in parallel to the oe-selftest job in separate `sandbox`.

yes, it depends on `conf/bblayers.conf` generated by meta-updater/scripts/envsetup.sh and content of which depends on the script param speechifying machine type what in turn has an impact on this https://github.com/advancedtelematic/meta-updater/blob/22165a78b34583c1389c0c9c5841c5377bad6e10/lib/oeqa/selftest/cases/updater_minnowboard.py#L14 :)

**Review by pattivacek — APPROVED** [review]
Looks fine to me. And if we need to update meta-updater-raspberrypi, that's also fine, although I still don't understand why that is working without this line but this isn't without it.

**Comment by lbonn** [comment]
Our oe-selftests are written so that they can be run with any machine used during the environment setup. eg: https://github.com/advancedtelematic/meta-updater/blob/22165a78b34583c1389c0c9c5841c5377bad6e10/lib/oeqa/selftest/cases/updater_minnowboard.py#L24 and https://github.com/advancedtelematic/meta-updater/blob/22165a78b34583c1389c0c9c5841c5377bad6e10/lib/oeqa/selftest/cases/updater_raspberrypi.py#L46.

It's indeed counter-intuitive but the raspberrypi cases work fine currently. I'm not sure why there were problems in this case.

**Comment by mike-sul** [comment]
I think, it has to do with the line #13 and #14 here https://github.com/advancedtelematic/meta-updater/blob/22165a78b34583c1389c0c9c5841c5377bad6e10/lib/oeqa/selftest/cases/updater_minnowboard.py#L14

**Comment by mike-sul** [comment]
The intel layer is added only if 'bitbake-layers add-layer" outputs it, and it won't output it unless you run the envsetup with intel-corei7-64.

**Comment by lbonn** [comment]
Isn't it the opposite? If `re.search` returns None, it means that it's not in the list.

The logic for the raspberrypi is the same and it seems to work there.

**Comment by mike-sul** [comment]
Well, something must have an impact on the test if  the envsetup is not run with intel-corei7-64, it didn't work for me without passing of that parameter.

**Pull request merged**
